pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

include ':app'

def capacitorSettings = new File(settingsDir, 'capacitor.settings.gradle')
if (capacitorSettings.exists()) {
    apply from: capacitorSettings
}
