export const MOROCCAN_ITEMS_DB = [
  { name: 'Danone', category: 'Gourmandises', estimatedPrice: 2.5, iconName: 'Milk' },
  { name: 'Oulmes', category: 'Essentiel', estimatedPrice: 6, iconName: 'CupSoda' },
  { name: 'Sidi Ali', category: 'Essentiel', estimatedPrice: 5, iconName: 'Droplets' },
  { name: 'Pain', category: 'Essentiel', estimatedPrice: 1.2, iconName: 'Wheat' },
  { name: 'Lait Jaouda', category: 'Essentiel', estimatedPrice: 3.5, iconName: 'Milk' },
  { name: 'Koutoubia', category: 'Protéines', estimatedPrice: 15, iconName: 'Beef' },
  { name: 'Fairy', category: 'Sanitaire', estimatedPrice: 13, iconName: 'Sparkles' },
  { name: 'Tide', category: 'Sanitaire', estimatedPrice: 15, iconName: 'Shirt' },
  { name: 'Bampers', category: 'Sanitaire', estimatedPrice: 60, iconName: 'Baby' },
  { name: 'Cafe', category: 'Gourmandises', estimatedPrice: 15, iconName: 'Coffee' },
  { name: 'Atai', category: 'Essentiel', estimatedPrice: 13, iconName: 'Leaf' },
  { name: 'Sucre', category: 'Essentiel', estimatedPrice: 6, iconName: 'Box' },
  { name: 'Huile Lesieur', category: 'Essentiel', estimatedPrice: 85, iconName: 'Droplet' },
  { name: 'Oeufs', category: 'Protéines', estimatedPrice: 1.5, iconName: 'Egg' },
  { name: 'Fromage Vache Qui Rit', category: 'Essentiel', estimatedPrice: 15, iconName: 'CheckCircle' },
  { name: 'Farine', category: 'Essentiel', estimatedPrice: 20, iconName: 'Wheat' },
  { name: 'Marlboro', category: 'Loisirs', estimatedPrice: 39, iconName: 'Cigarette' },
  { name: 'Hawai', category: 'Gourmandises', estimatedPrice: 6, iconName: 'CupSoda' },
  { name: 'Poms', category: 'Gourmandises', estimatedPrice: 6, iconName: 'CupSoda' },
  { name: 'Bimo', category: 'Gourmandises', estimatedPrice: 1.5, iconName: 'Cookie' },
  { name: 'Merendina', category: 'Gourmandises', estimatedPrice: 2, iconName: 'Cookie' },
  { name: 'Raibi Jamila', category: 'Gourmandises', estimatedPrice: 2.5, iconName: 'Milk' },
  { name: 'Papier Toilette', category: 'Sanitaire', estimatedPrice: 20, iconName: 'Scroll' },
  { name: 'Dentifrice Signal', category: 'Sanitaire', estimatedPrice: 15, iconName: 'Droplets' },
  { name: 'Savon', category: 'Sanitaire', estimatedPrice: 5, iconName: 'Droplets' },
  { name: 'Shampooing Cadum', category: 'Sanitaire', estimatedPrice: 18, iconName: 'Wind' },
  { name: 'Viande', category: 'Protéines', estimatedPrice: 90, iconName: 'Beef' },
  { name: 'Poulet', category: 'Protéines', estimatedPrice: 40, iconName: 'Drumstick' },
  { name: 'Poisson', category: 'Protéines', estimatedPrice: 50, iconName: 'Fish' },
  { name: 'Légumes', category: 'Plantes', estimatedPrice: 20, iconName: 'Carrot' },
  { name: 'Fruits', category: 'Plantes', estimatedPrice: 25, iconName: 'Apple' },
  { name: 'Glace', category: 'Gourmandises', estimatedPrice: 15, iconName: 'IceCream' }
];
