apply plugin: 'com.android.application'

android {
    namespace "com.hamza.masrof"
    compileSdk 34

    defaultConfig {
        applicationId "com.hamza.masrof"
        minSdk 22
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.getcapacitor:core:6.+'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
}
