name: Android Release Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
            
      - name: Find gradlew and build APK
        run: |
          # Trouver le dossier qui contient gradlew
          GRADLE_DIR=$(dirname $(find . -name "gradlew" | head -n 1))
          echo "Dossier gradle trouvé : $GRADLE_DIR"
          cd $GRADLE_DIR
          
          # Donner les droits d'exécution
          chmod +x ./gradlew
          
          # Nettoyer et compiler
          ./gradlew clean assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: masrof-app-debug
          path: '**/app/build/outputs/apk/debug/*.apk'
